### ISSUE TITLE
Add bash script

### ISSUE THREAD

**Issue by holmesal** [robinpowered/bifrost#2]
Should run apt-get to install all of the necessary libraries.
Should install forever and node.
Should install rbn.

**Comment by holmesal** [comment]
@mcos is on this.

**Comment by mcos** [comment]
This is done in https://github.com/robinpowered/robin-grid/pull/18, will pull it out into it's own module as soon as we open source this repo.

**Comment by holmesal** [comment]
Done since b7df8fad80

Not sure we need to pull this out into another repo. What would the advantage be?

**Comment by mcos** [comment]
Ah, I mistook this for the install script. :poop:
