### ISSUE TITLE
Create API for loading transports and interfaces as "middleware"

### ISSUE THREAD

**Issue by eliperkins** [robinpowered/bifrost#7]
Right now, transports and interfaces are loaded in via `config.json` in a way that is not always 100% useful. By utilizing an Express-like API a la `app.use(some_middleware)`, we can load in transports and interfaces in a safer fashion with a better way to customize for all use-cases.

**Comment by eliperkins** [comment]
lol

**Comment by holmesal** [comment]
@eliperkins anxiously awaiting this api, when will it be released?
